### ISSUE TITLE
ios项目 build时报错

### ISSUE THREAD

**Issue by liqinong** [442623641/cordova-plugin-aliyunpush#2]
ld: framework not found UTDID
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The following build commands failed:
        Ld build/emulator/newApp.app/newApp normal x86_64
(1 failure)
(node:6414) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/liqinong/Desktop/liqinong/newApp/newApp/platforms/ios/cordova/build-debug.xcconfig,-workspace,newApp.xcworkspace,-scheme,newApp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/liqinong/Desktop/liqinong/newApp/newApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/liqinong/Desktop/liqinong/newApp/newApp/platforms/ios/build/sharedpch
(node:6414) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6414) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 442623641** [comment]
@liqinong 
The UTDID.framework is not added correctly，provide info about syetem ，xocde environment

**Comment by liqinong** [comment]
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 5.0.13
    Node       : v8.11.1
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by 442623641** [comment]
@liqinong 
卸了重新安装

1.rm -f plugins
2.cordova plugin rm cordova-plugin-aliyunpush
3.cordova platform rm ios
4.cordova platform add ios
5.下载插件到项目根目录，run cordova plugin add ./cordova-plugin-aliyunpush --variable ANDROID_KEY=xxxxx --variable ANDROID_SECRET=xxxxx --variable IOS_KEY=xxxxx --variable IOS_SECRET=xxxxx
或
cordova plugin add https://github.com/442623641/cordova-plugin-aliyunpush.git --variable ANDROID_KEY=${ANDROID_KEY} --variable ANDROID_SECRET=${ANDROID_SECRET} --variable IOS_KEY=${IOS_KEY} --variable IOS_SECRET=${IOS_SECRET}

**Comment by liqinong** [comment]
我按照您提供的方法执行了之后，还是不行，提示相同的错误，之后我新创建了一个项目，安装后也出现了这个错误
Ld build/emulator/aliyun.app/aliyun normal x86_64
    cd /Users/liqinong/Desktop/liqinong/fork/aliyun/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/liqinong/Desktop/liqinong/fork/aliyun/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.3.sdk -L/Users/liqinong/Desktop/liqinong/fork/aliyun/platforms/ios/build/emulator -F/Users/liqinong/Desktop/liqinong/fork/aliyun/platforms/ios/build/emulator -Faliyun/Plugins/cordova-plugin-aliyunpush -filelist /Users/liqinong/Library/Developer/Xcode/DerivedData/aliyun-gzhwvndzsavirzaghsrljdivhplj/Build/Intermediates.noindex/aliyun.build/Debug-iphonesimulator/aliyun.build/Objects-normal/x86_64/aliyun.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/liqinong/Library/Developer/Xcode/DerivedData/aliyun-gzhwvndzsavirzaghsrljdivhplj/Build/Intermediates.noindex/aliyun.build/Debug-iphonesimulator/aliyun.build/Objects-normal/x86_64/aliyun_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/liqinong/Library/Developer/Xcode/DerivedData/aliyun-gzhwvndzsavirzaghsrljdivhplj/Build/Intermediates.noindex/aliyun.build/Debug-iphonesimulator/aliyun.build/aliyun.app-Simulated.xcent /Users/liqinong/Desktop/liqinong/fork/aliyun/platforms/ios/build/emulator/libCordova.a -weak_framework WebKit -lz -framework UserNotifications -lsqlite3 -lresolv -framework CoreTelephony -framework SystemConfiguration -framework AlicloudUtils -framework CloudPushSDK -framework UTDID -framework UTMini -Xlinker -dependency_info -Xlinker /Users/liqinong/Library/Developer/Xcode/DerivedData/aliyun-gzhwvndzsavirzaghsrljdivhplj/Build/Intermediates.noindex/aliyun.build/Debug-iphonesimulator/aliyun.build/Objects-normal/x86_64/aliyun_dependency_info.dat -o /Users/liqinong/Desktop/liqinong/fork/aliyun/platforms/ios/build/emulator/aliyun.app/aliyun
ld: framework not found UTDID
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by 442623641** [comment]
@liqinong 
fixed，framework依赖包损坏导致，重新安装
